### ISSUE TITLE
Build error with 0.14.0-alpha+1, when using MaterialStepper (StepDirective)

### ISSUE THREAD

**Issue by jbaxe2** [dart-lang/angular_components#436]
Hello,
I'm not sure if this is an issue for this package, or a different package (possibly angular or build_web_compiler?).  I am using Dart SDK 2.5.0.  Compiling with Dart2Js and DDC results in the same error.

I have an app that makes use of the MaterialStepper.  It works perfectly fine with 0.13.0+1.  However, I attempted to test out 0.14.0-alpha+1.  Attempting to build my project with the newer version results in an error with the template built for the MaterialStepper.  Here is the error I am receiving:

Error: A value of type 'String' can't be assigned to a variable of type 'bool'.
      this._StepDirective_5_9.canContinue = 'false';
                                            ^
Error: Compilation failed.

The complication works in the 'current' version (0.13.0+1).  With the newer version, somewhere along the way in building the template, it appears to be converting the StepDirective's canContinue field from a bool to a String, for which a later step in the build is expecting the bool.

Any ideas?

Thanks,
Joe
